language: scala

scala:
  - 2.10.6
  - 2.11.11
  - 2.12.2

jdk:
  - oraclejdk8

script: sbt ++$TRAVIS_SCALA_VERSION coverage test docs/tut coverageReport

after_success:
  - bash <(curl -s https://codecov.io/bash)
